### ISSUE TITLE
Unexpected token '.' for Web initial

### ISSUE THREAD

**Issue by tranquoccuonga3** [expo/sentry-expo#182] opened 2021-04-02 06:45 UTC
### Summary

The packed can't run on Web platform

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

^39.0.0

### Environment

Expo CLI 3.27.4 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\Admin\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ^39.0.0 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
      react-native-web: ^0.14.2 => 0.14.8
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

When I tried using Sentry-Expo with bare workflow. I got issues on Web

Hello everyone !

I using packed sentry-expo for 3 platform (Web, Android and iOS). Everything working well on native but when I tried with web initial then faced issues 

Thanks you so much.

![Screenshot_32](https://user-images.githubusercontent.com/28645627/113388914-47eed780-93b9-11eb-90ea-d08bed157412.png)
![Screenshot_33](https://user-images.githubusercontent.com/28645627/113388924-4b825e80-93b9-11eb-8443-8d8e36a50950.png)

**Comment by cruzach** [comment] 2021-04-02 13:47
Can you give the steps to reproduce this?

**Comment by tranquoccuonga3** [comment] 2021-04-04 01:57
> Can you give the steps to reproduce this?

Thanks for your take a look into my issue. 

Step 1: I install sentry-expo with version 3.1.3 and create Wrapper (SentryWrapper) to wrap the application.
Step 2: Follow documentation
```
Sentry.init({
  dsn: SENTRY_DSN,
  enableInExpoDevelopment: true,
  debug: true,
});
```

Step 3: I start run build project => Successful for Web and Native
Step 4: I open application on web with localhost:...... => The error occur as my mention above.

Thanks & Regards

**Comment by cruzach** [comment] 2021-06-23 19:53
Believe this is because you're using an older version of Node, but fixed in https://github.com/expo/sentry-expo/commit/52e1fbb4ca241c448141029efdde8c8272c64a19

**Closed by cruzach** 2021-06-23 19:53 UTC
