### ISSUE TITLE
[3.0.0-rc2] Sourcemap not found with expo-updates on Android

### ISSUE THREAD

**Issue by RodolfoGS** [expo/sentry-expo#134] opened 2020-07-25 15:30 UTC
### Summary of Issue 

I'm testing the `3.0.0-rc2`. If you install an update via expo-updates, Sentry can't found the sourcemaps.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.22.3
```

### Reproducible Demo

Repo: https://github.com/RodolfoGS/sentry-hook-issue

1. `git clone git@github.com:RodolfoGS/sentry-hook-issue.git`
2. `cd sentry-hook-issue`
3. `yarn install`
4. Configure the following files with your Sentry values (org, project, token and dsn)
```
 - android/sentry.properties
 - app.json
 - ios/sentry.properties
 - App.js
```
5. Build APK as release
6. Install in your device, run and tap on `Crash Now` button
7. The crash appears perfectly on Sentry, with their sourcemaps 👍
8. `expo publish`
9. Tap on `Update Now` button
10. Tap on `Crash Now` button
11. The crash appears on Sentry without their sourcemaps 👎

I'm experimenting this issue on Android, I'm not tested on iOS yet.

**Comment by RodolfoGS** [comment] 2020-07-25 15:54
Additional to this, when you send the first crash to Sentry (**step 6** of Reproducible Demo), Sentry show two issues related to tags. I don't know what is this.

![image](https://user-images.githubusercontent.com/870365/88460857-ffb00a80-ce64-11ea-80dc-94a7621a0798.png)

**Comment by cruzach** [comment] 2020-07-27 19:03
Hm I thought I had addressed this case, thanks for the issue

In your Sentry dashboard, is the issue in the appropriate `release`? i.e. the same version of `Updates.manifest.revisionId` you set the release to?

**Comment by RodolfoGS** [comment] 2020-07-27 19:44
Yes, the release match perfect and have the artifacts (sourcemaps). I attach screenshots.

Release: `1.0.0-r.lu7XwQK7E`

![image](https://user-images.githubusercontent.com/870365/88583858-6e809580-d016-11ea-99e0-4b333e665509.png)

![sentry](https://user-images.githubusercontent.com/870365/88584565-6d9c3380-d017-11ea-9fd1-4d98cd681ecd.png)

**Comment by pweisensee** [comment] 2020-08-03 13:53
@cruzach 
I'm having these same issues with an Expo 37 bare app on iOS. So I don't think it's an Android specific issue.

**Comment by cruzach** [comment] 2020-08-03 21:23
So i was able to reproduce this, but not consistently. On the same build & OTA update, sometimes it finds the sourcemaps and sometimes it doesn't. It actually looks like this could be an upstream issue? https://github.com/getsentry/sentry-react-native/issues/750

**Comment by pweisensee** [comment] 2020-08-03 22:23
@cruzach Do you think it could be fixed with this recent upstream PR? Or did you test with the latest of `sentry-react-native`?
 [getsentry/sentry-react-native/pull/1009](https://github.com/getsentry/sentry-react-native/pull/1009)

**Comment by cruzach** [comment] 2020-08-03 22:29
No I just tested that and am still getting the same behavior:

- build the app -> cause error-> sourcemaps work
- send out an OTA update -> download update -> error -> sourcemaps work
- reopen app after previous crash -> error -> sourcemaps DO NOT work

**Comment by cruzach** [comment] 2020-08-03 23:40
I believe I've identified a fix for this, will open a PR soon and release a new RC. Keeping you posted here

**Closed** 2020-08-04 22:15 UTC

**Comment by cruzach** [comment] 2020-08-04 22:20
Okay `sentry-expo@3.0.0-rc3` is published as `next`. @pweisensee I wasn't able to reproduce this on iOS so I have a feeling your issue is separate, so if you still see it on the next version please let me know
