### ISSUE TITLE
expo build:web fails

### ISSUE THREAD

**Issue by gidjituser** [expo/sentry-expo#95] opened 2019-12-15 22:09 UTC
building for web gives the following error

 web  Failed to compile.

xxxxxx/node_modules/sentry-expo/index.js 25:12
Module parse failed: Unexpected token (25:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
 
 class ExpoIntegration {
\>   static id = 'ExpoIntegration';
   name = ExpoIntegration.id;

Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by cruzach** [comment] 2019-12-16 18:32
closing as a duplicate of https://github.com/expo/sentry-expo/issues/77

**Closed by cruzach** 2019-12-16 18:32 UTC
