### ISSUE TITLE
API request failed - caused by: sentry reported an error: unknown error (http status: 413)

### ISSUE THREAD

**Issue by jurrianlammerts** [expo/sentry-expo#79] opened 2019-09-26 13:17 UTC
I am unable to get source maps to correctly work in sentry. I've followed the docs on [Expo](https://docs.expo.io/versions/latest/guides/using-sentry/), but i can't get it to work properly.

**Package.json**
```
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "expo": "^34.0.3",
    "expo-asset": "^5.0.0",
    "expo-barcode-scanner": "^5.0.1",
    "expo-camera": "^6.0.0",
    "expo-constants": "^6.0.0",
    "expo-font": "^6.0.1",
    "expo-localization": "^6.0.0",
    "expo-permissions": "^6.0.0",
    "mock-async-storage": "^2.2.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-dom": "^16.8.3",
    "react-native": "0.59.8",
    "react-native-camera": "^3.4.0",
    "react-native-elements": "^1.2.1",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-modal": "^11.3.1",
    "react-native-picker-select": "^6.3.3",
    "react-native-svg": "^9.9.4",
    "react-native-web": "^0.11.7",
    "react-navigation": "^3.12.1",
    "sentry-expo": "^2.0.0",
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "babel-preset-expo": "^5.1.0",
    "jest": "^24.9.0",
    "jest-expo": "^33.0.0",
    "jest-fetch-mock": "^2.1.2",
    "prettier": "1.18.2",
  }
}

```

**app.json**
```
{
  "expo": {
    "sdkVersion": "34.0.0",
    "platforms": ["ios", "android", "web"],
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": <organization>
            "project":<project>,
            "authToken": <token>,
            "url": <url>
          }
        }
      ]
    }
  }
}
```

**Output**
```
Running postPublish hook: sentry-expo/upload-sourcemaps
Created release 2.0.2-r.9a6oZ2pddP.

Error uploading sourcemaps to Sentry: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
Verify that your Sentry configuration in app.json is correct and refer to https://docs.expo.io/versions/latest/guides/using-sentry.html
Published
Your URL is

https://exp.host/<App>

› Closing Expo server
› Stopping Metro bundler
```

**Comment by cruzach** [comment] 2019-09-27 14:58
Is this only an issue on `sentry-expo` v2? 

Are you making use of breadcrumbs? I've seen some other 413 error code reports that were due to breadcrumb size.

**Comment by jurrianlammerts** [comment] 2019-09-30 12:36
Yes, this issue is related to `sentry-expo` v2 and I'm not using breadcrumbs. I got the most minimal setup for Sentry in App.js.

```
Sentry.init({
  dsn:
    '...',
  enableInExpoDevelopment: true,
  debug: true
});

```

**Comment by cruzach** [comment] 2019-09-30 21:01
Are you able to get this error on a blank expo project? A way for me to reproduce this locally would help a lot

**Comment by jurrianlammerts** [comment] 2019-10-03 11:35
I've made a snack with the code: https://snack.expo.io/@jurrian-l/dda5c7. Let me know if I need to provide more context about the project and its dependencies.

**Comment by cruzach** [comment] 2019-10-03 20:14
Same set-up I have. I'm wondering if this is due to you self-hosting sentry? Could you try it without the optional `url` setting in the postPublish config?

**Comment by vincent-lu** [comment] 2019-10-04 03:08
Having the same problem; same set up worked fine when using offical sentry.io but got 413 error when moved to use self hosted sentry.

**Comment by liogate** [comment] 2019-12-01 21:03
Hello !
I was running into the same issue and I found that it was from my ingress wasn't allowing large entity payload.

Fixed by adding annotation on my ingress:
nginx.ingress.kubernetes.io/proxy-body-size=0

If you're using nginx, update your proxy using this in your host config:
```
server {
    ...
    client_max_body_size 100M;
}
```

Enjoy ! 🎉

**Comment by cruzach** [comment] 2019-12-16 18:36
@jurrianlammerts can you let me know if the above solution works for you? Looks like this should only be a problem if you're self-hosting sentry

**Comment by jurrianlammerts** [comment] 2019-12-16 18:43
I've managed to get it working on a self hosted domain by using `react-native-sentry` (^0.43.2) instead of `sentry-expo`.  The solution given above won't work in my case, because I'm not using nginx. However thank you for your help!

**Closed** 2019-12-16 19:22 UTC
