### ISSUE TITLE
Promise rejection: SentryError: Native is disabled

### ISSUE THREAD

**Issue by laupow** [expo/sentry-expo#218] opened 2021-10-21 14:57 UTC
### Summary

Trying to get Sentry's performance/tracing enabled on web & mobile.

The tracing works on web builds, but not yet on for mobile and there are promise rejections.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

```
  Expo CLI 4.12.6 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.0 => 0.16.0 
    npmGlobalPackages:
      expo-cli: 4.12.6
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

I'll work on a demo. I'm new to the frameworks.

Here's a code mashup of Sentry.init()

```
const settings = {
	enabled: true,
	dsn: Constants.manifest.extra?.sentry.dsn,
	debug: true,
	enableInExpoDevelopment: true,
};

let routingInstrumentation = null;
if (Platform.OS !== 'web') {
	routingInstrumentation = new SentrySDK.Native.ReactNavigationInstrumentation();
}

if (Platform.OS === 'web') {
	settings.integrations = [new TracingIntegrations.BrowserTracing({
			tracingOrigins: ['localhost', 'domain.com', /^\//],
	})];
	SentrySDK.Browser.init(settings);
} else {
	settings.integrations = [
		new SentrySDK.Native.ReactNativeTracing({
			tracingOrigins: ['localhost', 'domain.com', /^\//],
			routingInstrumentation,
		}),
	];
	SentrySDK.init(settings);
}
```

```
[Unhandled promise rejection: SentryError: Native is disabled]
at node_modules/@sentry/react-native/node_modules/@sentry/utils/dist/error.js:9:20 in SentryError
at node_modules/@sentry/react-native/dist/js/wrapper.js:395:26 in <global>
at node_modules/@sentry/react-native/dist/js/tracing/reactnativetracing.js:4:0 in <global>
at node_modules/@sentry/react-native/dist/js/tracing/index.js:1:0 in <global>
at node_modules/@sentry/react-native/dist/js/measurements.js:2:0 in <global>
at node_modules/@sentry/react-native/dist/js/index.js:7:0 in <global>
at node_modules/sentry-expo/build/integrations/bare.js:30:30 in <global>
at node_modules/sentry-expo/build/sentry.js:28:22 in <global>
at node_modules/sentry-expo/build/index.js:26:20 in <global>
at src/lib/sentry.ts:2:0 in <global>
at src/index.tsx:16:0 in <global>
at http://127.0.0.1:19000/src/index.tsx.bundle?platform=ios&dev=true&hot=false&minify=false:388768:3 in global code

```

**Comment by cruzach** [comment] 2021-10-21 17:55
Hi! this is a duplicate of https://github.com/expo/sentry-expo/issues/216

this is addressed in the docs in https://github.com/expo/sentry-expo/commit/6713f6718b6bc1c1691d387a7f9c30bdfdefcc8f

**Closed as completed by cruzach** 2021-10-21 17:55 UTC

**Comment by bpmct** [comment] 2021-11-12 03:16
I'm using Expo Go, not EAS, and running into this whenever I try to use `routingInstrumentation`

**Comment by remcorakers** [comment] 2021-12-30 09:33
@cruzach the error message in this issue is different: `SentryError: Native Client is not available, can't start on native` vs. `SentryError: Native is disabled`. Looks like it's not resolved after all 😕  See also https://github.com/expo/sentry-expo/issues/216#issuecomment-1002944278.

**Comment by alexis-regnaud** [comment] 2022-01-08 22:04
I have the same issue on Android (`SentryError: Native is disabled`)

**Comment by geraldosalazar16** [comment] 2022-03-11 15:49
Is it possible that this issue is reopen? I am experiencing the same issue with a brand new expo app
`"dependencies": {
    "@sentry/react-native": "^3.3.2",
    "expo": "~44.0.0",
    "expo-application": "~4.0.1",
    "expo-constants": "~13.0.1",
    "expo-device": "~4.1.0",
    "expo-status-bar": "~1.2.0",
    "expo-tracking-transparency": "~2.1.0",
    "expo-updates": "~0.11.6",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "sentry-expo": "^4.0.0"
  },`

**Comment by MorenoMdz** [comment] 2022-03-16 13:42
The same thing is happening in our project, it is most likely this issue still happening.

**Comment by jimmihagenTrifecta** [comment] 2022-03-30 00:57
Please reopen this, or open another similar ticket for our Expo Sentry issue :

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

We get these stack traces while using Sentry with Expo. Sentry.Native.nativeCrash() does not crash, uncaught errors are sent to the backend but produce the backtrace above. 

It looks like messages and errors are making it into the service. Sentry.Native.captureMessage() does not produce the stack trace.

**Comment by jimmihagenTrifecta** [comment] 2022-03-30 01:29
I don't think this is the same as the original issue in this ticket, since the stacktrace is different, but we're seeing this as well.

**Comment by jimmihagenTrifecta** [comment] 2022-03-30 22:53
@geraldosalazar16 @MorenoMdz please see https://github.com/expo/sentry-expo/issues/243 , is this more similar to what we're seeing?

**Comment by daveslutzkin** [comment] 2022-04-04 02:44
Yes, this is happening for us with a very new almost empty expo project on v44. It happens whether or not we use `routingInstrumentation`, though that triggers it early because it tries to log route changes during startup of the app.

Logs:
```
› Opening on iOS...
› Opening exp://192.168.0.104:19000 on iPhone 12 Pro
› Press ? │ show all commands
iOS Bundling complete 8918ms
iOS Running app on iPhone 12 Pro
Sentry Logger [Log]: Integration installed: Release
Sentry Logger [Log]: Integration installed: InboundFilters
Sentry Logger [Log]: Integration installed: FunctionToString
Sentry Logger [Log]: Integration installed: Breadcrumbs
Sentry Logger [Log]: Integration installed: LinkedErrors
Sentry Logger [Log]: Integration installed: Dedupe
Sentry Logger [Log]: Integration installed: UserAgent
Sentry Logger [Log]: Integration installed: EventOrigin
Sentry Logger [Log]: Integration installed: SdkInfo
Sentry Logger [Log]: Integration installed: DebugSymbolicator
Sentry Logger [Log]: Unhandled promise rejections will be caught by Sentry.
Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
Sentry Logger [Log]: Integration installed: ExpoManagedIntegration
Sentry Logger [Log]: Integration installed: RewriteFrames
Sentry Logger [Log]: [ReactNativeTracing] Native frames instrumentation initialized.
Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 868f48e2f9c460cf
Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
Sentry Logger [Log]: Starting heartbeat
Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
Sentry Logger [Log]: Integration installed: ReactNativeTracing
Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 85b148d8d40d5717
Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
Sentry Logger [Log]: Starting heartbeat
Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
Sentry Logger [Log]: [Tracing] pushActivity: 9cd626c4ac4402ac
Sentry Logger [Log]: [Tracing] new activities count 1

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Log]: [Tracing] popActivity 9cd626c4ac4402ac
Sentry Logger [Log]: [Tracing] new activities count 0
Sentry Logger [Log]: Setting idle transaction on scope. Span ID: b8a6871c23da3362
Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
Sentry Logger [Log]: Starting heartbeat
Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
Sentry Logger [Log]: [Tracing] pushActivity: aadc175f8a632f31
Sentry Logger [Log]: [Tracing] new activities count 1
Sentry Logger [Log]: [Tracing] popActivity aadc175f8a632f31
Sentry Logger [Log]: [Tracing] new activities count 0

Sentry Logger [Warn]:, Event dropped due to being a duplicate of previously captured event.
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/browser/dist/integrations/dedupe.js:21:50 in addGlobalEventProcessor$argument_0
at node_modules/@sentry/hub/dist/scope.js:376:38 in utils_1.SyncPromise$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:83:20 in SyncPromise
at node_modules/@sentry/hub/dist/scope.js:370:15 in Scope.prototype._notifyEventProcessors
at node_modules/@sentry/hub/dist/scope.js:383:25 in utils_1.SyncPromise$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:83:20 in SyncPromise
at node_modules/@sentry/hub/dist/scope.js:370:15 in Scope.prototype._notifyEventProcessors
at node_modules/@sentry/hub/dist/scope.js:383:25 in utils_1.SyncPromise$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:83:20 in SyncPromise
at node_modules/@sentry/hub/dist/scope.js:370:15 in Scope.prototype._notifyEventProcessors
at node_modules/@sentry/hub/dist/scope.js:379:56 in result.then$argument_0

Sentry Logger [Error]:, [SentryError: An event processor returned null, will not send event.]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:95:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:93:22 in Logger.prototype.error
at node_modules/@sentry/core/dist/baseclient.js:406:38 in _processEvent.then$argument_1
at node_modules/@sentry/utils/dist/syncpromise.js:116:46 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:77:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:46:12 in _reject
at node_modules/@sentry/utils/dist/syncpromise.js:119:34 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:77:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:46:12 in _reject
at node_modules/@sentry/utils/dist/syncpromise.js:112:30 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:77:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:46:12 in _reject
at node_modules/@sentry/utils/dist/syncpromise.js:106:34 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:74:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:42:12 in _resolve
at node_modules/@sentry/utils/dist/syncpromise.js:103:35 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:74:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:42:12 in _resolve
at node_modules/@sentry/utils/dist/syncpromise.js:103:47 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:74:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:124:12 in SyncPromise$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:83:20 in SyncPromise
at node_modules/@sentry/utils/dist/syncpromise.js:92:15 in SyncPromise.prototype.then
at node_modules/@sentry/hub/dist/scope.js:379:56 in result.then$argument_0

Sentry Logger [Log]: Setting idle transaction on scope. Span ID: 896082bcaa01753b
Sentry Logger [Log]: [Tracing] starting navigation transaction - Route Change
Sentry Logger [Log]: Starting heartbeat
Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
Sentry Logger [Log]: [ReactNativeTracing] Starting navigation transaction "Route Change" on scope
Sentry Logger [Log]: [Tracing] pushActivity: 8ce549df0de694d2
Sentry Logger [Log]: [Tracing] new activities count 1
Sentry Logger [Log]: [Tracing] popActivity 8ce549df0de694d2
Sentry Logger [Log]: [Tracing] new activities count 0
Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2022-04-04T02:42:43.111Z navigation
Sentry Logger [Log]: [Tracing] flushing IdleTransaction
Sentry Logger [Log]: [Measurements] Adding measurements to transaction {
  "stall_count": {
    "value": 4
  },
  "stall_total_time": {
    "value": 975.97021484375
  },
  "stall_longest_time": {
    "value": 414.866455078125
  }
}
Sentry Logger [Log]: [Tracing] Finishing navigation transaction: login-opening.

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2022-04-04T02:42:43.533Z navigation
Sentry Logger [Log]: [Tracing] flushing IdleTransaction
Sentry Logger [Log]: [Measurements] Adding measurements to transaction {
  "stall_count": {
    "value": 1
  },
  "stall_total_time": {
    "value": 227.343994140625
  },
  "stall_longest_time": {
    "value": 227.343994140625
  }
}
Sentry Logger [Log]: [Tracing] Finishing navigation transaction: login-doLogin.

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2022-04-04T02:42:43.776Z navigation
Sentry Logger [Log]: [Tracing] flushing IdleTransaction
Sentry Logger [Log]: [Measurements] Adding measurements to transaction {
  "stall_count": {
    "value": 1
  },
  "stall_total_time": {
    "value": 122.44482421875
  },
  "stall_longest_time": {
    "value": 122.44482421875
  }
}
Sentry Logger [Log]: [Tracing] Finishing navigation transaction: login-afterLogin.

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Possible Unhandled Promise Rejection (id: 0):
SentryError: Native is disabled

Sentry Logger [Warn]:, Event dropped due to being internal Sentry Error.
Event: SentryError: Native is disabled
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/core/dist/integrations/inboundfilters.js:58:12 in _shouldDropEvent
at node_modules/@sentry/core/dist/integrations/inboundfilters.js:29:43 in addGlobalEventProcessor$argument_0
at node_modules/@sentry/hub/dist/scope.js:376:38 in utils_1.SyncPromise$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:83:20 in SyncPromise
at node_modules/@sentry/hub/dist/scope.js:370:15 in Scope.prototype._notifyEventProcessors
at node_modules/@sentry/hub/dist/scope.js:379:56 in result.then$argument_0

Sentry Logger [Error]:, [SentryError: An event processor returned null, will not send event.]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:95:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:93:22 in Logger.prototype.error
at node_modules/@sentry/core/dist/baseclient.js:406:38 in _processEvent.then$argument_1
at node_modules/@sentry/utils/dist/syncpromise.js:116:46 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:77:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:46:12 in _reject
at node_modules/@sentry/utils/dist/syncpromise.js:119:34 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:77:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:46:12 in _reject
at node_modules/@sentry/utils/dist/syncpromise.js:112:30 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:77:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:46:12 in _reject
at node_modules/@sentry/utils/dist/syncpromise.js:106:34 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:74:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:42:12 in _resolve
at node_modules/@sentry/utils/dist/syncpromise.js:103:35 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:74:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:59:12 in _setResult
at node_modules/@sentry/utils/dist/syncpromise.js:42:12 in _resolve
at node_modules/@sentry/utils/dist/syncpromise.js:103:47 in <anonymous>
at node_modules/@sentry/utils/dist/syncpromise.js:74:20 in cachedHandlers.forEach$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:68:12 in _executeHandlers
at node_modules/@sentry/utils/dist/syncpromise.js:124:12 in SyncPromise$argument_0
at node_modules/@sentry/utils/dist/syncpromise.js:83:20 in SyncPromise
at node_modules/@sentry/utils/dist/syncpromise.js:92:15 in SyncPromise.prototype.then
at node_modules/@sentry/hub/dist/scope.js:379:56 in result.then$argument_0

Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2022-04-04T02:42:44.104Z navigation
Sentry Logger [Log]: [Tracing] flushing IdleTransaction
Sentry Logger [Log]: [Measurements] Adding measurements to transaction {
  "stall_count": {
    "value": 0
  },
  "stall_total_time": {
    "value": 0
  },
  "stall_longest_time": {
    "value": 0
  }
}
Sentry Logger [Log]: [Tracing] Finishing navigation transaction: tabs-home.

Sentry Logger [Warn]:, [SdkInfo] Native SDK Info retrieval failed...something could be wrong with your Sentry installation:
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:28:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Warn]:, [SentryError: Native is disabled]
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:81:12 in consoleSandbox$argument_0
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:34:25 in consoleSandbox
at node_modules/sentry-expo/node_modules/@sentry/utils/dist/logger.js:79:22 in Logger.prototype.warn
at node_modules/@sentry/react-native/dist/js/integrations/sdkinfo.js:29:20 in __awaiter$argument_3
at node_modules/tslib/tslib.js:113:50 in rejected

Sentry Logger [Log]: Not capturing exception because it's already been captured.
Possible Unhandled Promise Rejection (id: 1):
SentryError: Native is disabled
Sentry Logger [Log]: Not capturing exception because it's already been captured.
Possible Unhandled Promise Rejection (id: 2):
SentryError: Native is disabled
Sentry Logger [Log]: Not capturing exception because it's already been captured.
Possible Unhandled Promise Rejection (id: 3):
SentryError: Native is disabled
Sentry Logger [Log]: Not capturing exception because it's already been captured.
Possible Unhandled Promise Rejection (id: 4):
SentryError: Native is disabled
Sentry Logger [Log]: Not capturing exception because it's already been captured.
Possible Unhandled Promise Rejection (id: 5):
SentryError: Native is disabled
Sentry Logger [Log]: Not capturing exception because it's already been captured.
Possible Unhandled Promise Rejection (id: 6):
SentryError: Native is disabled
Sentry Logger [Log]: [NativeFrames] Native frames timed out for navigation transaction login-opening. Not adding native frames measurements.
Sentry Logger [Log]: [NativeFrames] Native frames timed out for navigation transaction login-doLogin. Not adding native frames measurements.
Sentry Logger [Log]: [NativeFrames] Native frames timed out for navigation transaction login-afterLogin. Not adding native frames measurements.
Sentry Logger [Log]: [NativeFrames] Native frames timed out for navigation transaction tabs-home. Not adding native frames measurements.
```

**Comment by daveslutzkin** [comment] 2022-04-04 03:05
In our case it happens even when passing in `enableNative: false` to expo-sentry `init`.

However, it appears that the reports still come through to Sentry. So I suppose we just have to ignore the reams of error messages this generates, until someone gets around to investigating it?

**Comment by brentvatne** [comment] 2022-06-17 01:27
hi there! is there a particular reason why folks want to enable sentry in development?

the idea behind the `enableInExpoDevelopment` was to allow you to verify that the integration is correct, but if you leave this enabled, you will get many exceptions reported to sentry that are unnecessary.

it is expected to see something like "Sentry Logger [Warn]:, [SentryError: Native is disabled]" in Expo Go because the native sentry SDK is not installed there.

here's an example of a config where you do not receive such a warning in Expo Go:

```
Sentry.init({
  dsn: "....",
  enableInExpoDevelopment: false, // or leave this out, it will be the default
});
```

feel free to toggle `false` to `true` when you want to test the integration with the sentry backend

**Comment by jimmihagenTrifecta** [comment] 2022-06-17 01:42
> is there a particular reason why folks want to enable sentry in development?

we have a QA team test in various environments, most of which are not production. Sometimes it's very helpful to enable Sentry in those environments in order to collect data. Since Sentry filters based on environment, it's not an issue in any manner. Why would we not?

**Comment by lukewlms** [comment] 2023-05-24 20:45
In my case I see: " WARN  Sentry Logger [warn]: Event was skipped as native SDK is not enabled."

So contrary to what @brentvatne suggested, it seems I can't currently test the backend integration from Expo Go.  Nothing has shown up in Sentry.io so I'm not sure it's going to correctly connect when in production.
