### ISSUE TITLE
Native Client is not available error when debug is set to false in Sentry.init call

### ISSUE THREAD

**Issue by mtakac** [expo/sentry-expo#180] opened 2021-03-15 11:55 UTC
### Summary

I set up expo sentry in our app. At first, everything seemed to be working, but then I tried to disable debug in development and I now I cannot start the app, because of this error: SentryError: Native Client is not available, can't start on native.

This is my config. When I set `debug` to `true` it works again.

```
Sentry.init({
  dsn: SENTRY_DSN,
  enableInExpoDevelopment: false,
  debug: false,
});
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

39

### Environment

Expo CLI 4.3.0 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.8.4 - /Users/mtakac/.rvm/rubies/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 23, 25, 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-23 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.4 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Just start sentry in App.js with disabled debug mode:

```
Sentry.init({
  dsn: SENTRY_DSN,
  enableInExpoDevelopment: false,
  debug: false,
});
```

**Comment by cruzach** [comment] 2021-03-19 15:23
What version of `sentry-expo`? This could be a duplicate of [any of these issues](https://github.com/expo/sentry-expo/search?q=Native+Client+is+not+available%2C+can%27t+start+on+native&type=issues)

**Comment by mtakac** [comment] 2021-03-19 22:45
Hi @cruzach. Sorry I forgot to mention `sentry-expo` version. I am using `v 3.0.5`. I've seen the issues you linked above, unfortunately they are all closed without any resolution that would work for me. 

As for the repro of the issue: I believe it happens as soon as you set `debug` to `false`. I am not sure what else to add to the repro steps but please let me know if there's anything more I can do to help you find the issue.

**Comment by Neodern** [comment] 2021-03-24 19:10
Same problem as this issue: https://github.com/expo/sentry-expo/issues/178
With this configuration and latest release of sentry-expo : 

```
Sentry.init({
  dsn: "blablabla",
  enableNative: Device.isDevice,
  enableInExpoDevelopment: Device.isDevice,
  release: version,
  environment: env,
  integrations: (integrations) => (isDev ? [...integrations, new Debug() as Integration] : integrations),
  debug: env !== "production",
  enabled: !isDev,
});
```

**Comment by cruzach** [comment] 2021-03-30 17:31
@Neodern you have `enableNative: true`, which is why it's trying to initialize the native client. Be sure you:
- are in the bare workflow
- have `@sentry/react-native` in your dependencies
- run `npx pod-install` for iOS

**Comment by Neodern** [comment] 2021-03-30 18:43
@cruzach Oh. I'm using the managed workflow but it was working before. Removed `enableNative` and it's working as expected now. Thanks !

**Comment by cruzach** [comment] 2021-06-23 18:09
Closing since the above issue is resolved, and still haven't been able to repro @mtakac's original issue

**Closed by cruzach** 2021-06-23 18:09 UTC
