### ISSUE TITLE
failure to generate bundle on EAS Build

### ISSUE THREAD

**Issue by giautm** [expo/sentry-expo#187] opened 2021-05-09 12:41 UTC
Hi, I just trying to use sentry-expo plugin on EAS Build. I have config correct sentry-expo, but the build was failure with following errors:

```sh
+ /Users/expo/workingdir/build/node_modules/@sentry/cli/sentry-cli /Users/expo/workingdir/build/node_modules/react-native/cli.js bundle --entry-file ./__generated__/AppEntry.js --platform ios --dev false --reset-cache --bundle-output /Users/expo/Library/Developer/Xcode/DerivedData/XXXXXXXXXX/Build/Intermediates.noindex/ArchiveIntermediates/XXXXXXXXXX/BuildProductsPath/Release-iphoneos/XXXXXXXXXX.app/main.jsbundle --assets-dest /Users/expo/Library/Developer/Xcode/DerivedData/XXXXXXXXXX/Build/Intermediates.noindex/ArchiveIntermediates/XXXXXXXXXX/BuildProductsPath/Release-iphoneos/XXXXXXXXXX.app --sourcemap-output /Users/expo/Library/Developer/Xcode/DerivedData/XXXXXXXXXX/Build/Intermediates.noindex/ArchiveIntermediates/XXXXXXXXXX/IntermediateBuildFilesPath/XXXXXXXXXX.build/Release-iphoneos/XXXXXXXXXX.build/DerivedSources/main.jsbundle.map
error Invalid platform "ios" selected.
info Available platforms are: "native". If you are trying to bundle for an out-of-tree platform, it may not be installed.
error Bundling failed. Run CLI with --verbose flag for more details.
```

**Comment by giautm** [comment] 2021-05-10 10:47
Hey @cruzach, Can you take a look at this issue? I think issue related to `withSentryIOS.ts` script.

**Comment by cruzach** [comment] 2021-05-11 15:49
I need to know your app configuration as well

**Comment by giautm** [comment] 2021-05-11 15:59
It is hard to reproduce right because my project is a part of a mono repo. This is a diff between before & after I apply the `sentry-expo` plugin.
https://gist.github.com/giautm/9a6403cc46dceaa143269ff2d4695f5f/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2

the config is mostly the same.
```json
    "plugins": ["sentry-expo"],
    "hooks": {
      "postPublish": [
        {
          "config": {
            "authToken": "xxxxx",
            "organization": "sentry",
            "project": "freelancer",
            "url": "https://sentry-aws.aaaaaaa.xyz"
          },
          "file": "sentry-expo/upload-sourcemaps"
        },
```

**Comment by giautm** [comment] 2021-05-13 04:40
Hey @cruzach, This is my reproduce repo: https://github.com/giautm/eas-monorepo-example/compare/main...giautm:issue/sentry-expo

This is the build ID with error: `8b3ad330-7beb-4ade-bf59-4fb75cdae2c7`. Can you take a look?

```
+ CONFIG_ARG=
+ BUNDLE_FILE=/Users/expo/Library/Developer/Xcode/DerivedData/easmonorepoappmanaged-aprsyiyhsnipjoecftblhjhrythe/Build/Intermediates.noindex/ArchiveIntermediates/easmonorepoappmanaged/BuildProductsPath/Release-iphoneos/sentry-expo.app/main.jsbundle
+ /Users/expo/workingdir/build/node_modules/@sentry/cli/sentry-cli /Users/expo/workingdir/build/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/expo/Library/Developer/Xcode/DerivedData/easmonorepoappmanaged-aprsyiyhsnipjoecftblhjhrythe/Build/Intermediates.noindex/ArchiveIntermediates/easmonorepoappmanaged/BuildProductsPath/Release-iphoneos/sentry-expo.app/main.jsbundle --assets-dest /Users/expo/Library/Developer/Xcode/DerivedData/easmonorepoappmanaged-aprsyiyhsnipjoecftblhjhrythe/Build/Intermediates.noindex/ArchiveIntermediates/easmonorepoappmanaged/BuildProductsPath/Release-iphoneos/sentry-expo.app --sourcemap-output /Users/expo/Library/Developer/Xcode/DerivedData/easmonorepoappmanaged-aprsyiyhsnipjoecftblhjhrythe/Build/Intermediates.noindex/ArchiveIntermediates/easmonorepoappmanaged/IntermediateBuildFilesPath/easmonorepoappmanaged.build/Release-iphoneos/easmonorepoappmanaged.build/DerivedSources/main.jsbundle.map
error Invalid platform "ios" selected.
info Available platforms are: "native". If you are trying to bundle for an out-of-tree platform, it may not be installed.
error Bundling failed. Run CLI with --verbose flag for more details.
Error: Bundling failed
    at buildBundle (/Users/expo/workingdir/build/node_modules/@react-native-community/cli/build/commands/bundle/buildBundle.js:85:11)
    at async Command.handleAction (/Users/expo/workingdir/build/node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Comment by cruzach** [comment] 2021-05-13 13:29
@giautm this might be a relevant issue for you to look at - https://github.com/react-native-community/cli/issues/656

**Comment by giautm** [comment] 2021-05-13 17:23
Hi, I found the fix. Put `react-native` in workspace `package.json` will fix the issue; [see the diff](https://github.com/giautm/eas-monorepo-example/commit/5aa3f809a12d0992a9ce59216209ec5842ae3ead)
```
{
  "dependencies": {
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"
  },
}
```

The XCode log will be changed as:
```diff
  + case "$CONFIGURATION" in
  + DEV=false
- +++ dirname /Users/expo/workingdir/build/node_modules/react-native/scripts/react-native-xcode.sh
+ +++ dirname /Users/expo/workingdir/build/apps/managed/node_modules/react-native/scripts/react-native-xcode.sh
- ++ cd /Users/expo/workingdir/build/node_modules/react-native/scripts/..
+ ++ cd /Users/expo/workingdir/build/apps/managed/node_modules/react-native/scripts/..
  ++ pwd
- + REACT_NATIVE_DIR=/Users/expo/workingdir/build/node_modules/react-native
+ + REACT_NATIVE_DIR=/Users/expo/workingdir/build/apps/managed/node_modules/react-native
- + PROJECT_ROOT=/Users/expo/workingdir/build/node_modules/react-native/../..
+ + PROJECT_ROOT=/Users/expo/workingdir/build/apps/managed/node_modules/react-native/../..
  + cd /Users/expo/workingdir/build/node_modules/react-native/../..
  + '[' -z /Users/expo/.nvm ']'
  + [[ -n '' ]]
  + [[ -s index.ios.js ]]
```

But, I don't like the solution. I have tried to set `PROJECT_ROOT` to `$PROJECT_DIR/..` with `eas.json`, but It doesn't work.
```json
        "env": {
          "PROJECT_ROOT": "$PROJECT_DIR/.."
        }
```

It printed the plain text to the console as:
```
+ REACT_NATIVE_DIR=/Users/expo/workingdir/build/node_modules/react-native
+ PROJECT_ROOT='$PROJECT_DIR/..'
+ cd '$PROJECT_DIR/..'
```

**Comment by cruzach** [comment] 2021-05-13 17:42
This is an issue with monorepo setup, not with `sentry-expo`, so I'm going to close this issue

@giautm can you take a look at this monorepo example and try to proceed from there- https://github.com/byCedric/eas-monorepo-example? There's a couple different options for you to achieve what you're looking for here

I think that the `env` field can only be used for string values: https://docs.expo.io/build/eas-json/

**Closed by cruzach** 2021-05-13 17:42 UTC
Labels: needs reproducible demo

**Comment by giautm** [comment] 2021-05-13 18:08
My reproduce repo is a fork of https://github.com/byCedric/eas-monorepo-example. ;)

I have faced [other issues](https://github.com/expo/expo/issues?q=is%3Aissue+eas+author%3Agiautm ) when trying to use EAS build with mono-repo. I have a little experience. ;)

**Comment by giautm** [comment] 2021-05-15 03:40
Hey @cruzach, after I put `react-native` as a dependency in `package.json`, the build success but the app can't open.
> `Module AppRegistry is not a registered callable module (calling runApplication)`

There is no error with the code, I try to rebuild the app many times with a single commit that adds `react-native` then it can't open.

```json
{
  "dependencies": {
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"
  },
}
```

Is there any way to fix the issue? 😢

**Comment by cruzach** [comment] 2021-05-15 14:06
@giautm that error message can be the result of a lot of different issues, you'll have to go through some [manual debugging](https://github.com/expo/fyi/blob/master/manual-debugging.md) to investigate this further

**Comment by giautm** [comment] 2021-05-15 21:05
> @giautm that error message can be the result of a lot of different issues, you'll have to go through some [manual debugging](https://github.com/expo/fyi/blob/master/manual-debugging.md) to investigate this further 

Hey, I have try to debug.  But on iOS, there is no error logged to the console.

I decide to remove this plugin and the fix (put "react-native" in "package.json"). I don't have enough time to find the root cause.

**Comment by parisholley** [comment] 2021-07-24 12:40
i was able to reproduce this, there is some issue with post publish step in an EAS build, works fine (uploads code) using `expo build:ios`. Same behavior happens locally and remote, with simply a mainjs bundle missing but no error output from the postpublish step. i've tried symlinking all of the sentry modules (@sentry/....) but that didn't help.

https://github.com/parisholley/expo-bugs

**Comment by cruzach** [comment] 2021-07-24 12:43
https://docs.expo.io/build-reference/migrating/#no-more-automatic-publishing-before-building

Make sure you follow the docs and add the config plugin- https://github.com/expo/sentry-expo#step-3

**Comment by parisholley** [comment] 2021-07-24 12:45
i did, it ONLY works if the plugin is defined, soon as you add the hook, the build breaks

**Comment by parisholley** [comment] 2021-07-24 12:58
`Because we no longer publish at build time, postPublish hooks in app.json will not be executed on build` does not appear to be the case anymore. when i run `expo prebuild`, I still see a "Upload Debug Symbols to Sentry" step in my `pbxproj`

**Comment by byCedric** [comment] 2021-07-26 10:42
Please see the EAS monorepo example with Sentry and hooks configured: https://github.com/byCedric/eas-monorepo-example/tree/main/apps/with-sentry.

**Comment by parisholley** [comment] 2021-07-26 12:22
reposting here: @byCedric it is very possible my error is iOS specific and your example doesn't have a working iOS test :) from what i can tell, the only difference between the example and the repo i provided is symlinks (which i've already tried linking sentry-expo and every @sentry/* dependency with no success)

**Comment by cruzach** [comment] 2021-07-26 13:05
>when i run expo prebuild, I still see a "Upload Debug Symbols to Sentry" step in my pbxproj

Your sourcemaps are still uploaded, but it's done with Sentry's native build scripts, not with your post publish hook

**Comment by parisholley** [comment] 2021-07-28 14:09
@byCedric were you able to confirm if this is an iOS specific issue? no rush on a fix, just need to know if I need to dig more :)

**Comment by byCedric** [comment] 2021-07-28 14:50
> @byCedric were you able to confirm if this is an iOS specific issue? no rush on a fix, just need to know if I need to dig more :)

It looks like it might be an issue with Sentry's CLI and finding the proper folder where the project is located in. This only seems to happen for monorepos though. I [added an `ios` branch to the example](https://github.com/byCedric/eas-monorepo-example/blob/ios-sentry/apps/with-sentry/patches/sentry-expo%2B4.0.1.patch) I linked earlier, which should (temporarily) fix the issue.

If you can try that, it should work for your iOS builds 😄

**Comment by parisholley** [comment] 2021-07-28 15:51
@byCedric that patch fixed eas remote build :) doesn't work for `--local` but I can live with that

**Comment by byCedric** [comment] 2021-07-28 16:13
Good to know! We are making progress on removing monorepo weirdness. We will definitely have something better for SDK 43!

**Comment by giautm** [comment] 2021-07-28 19:31
Thanks @byCedric for the fix. I hope it soon plant to production.

**Comment by jereztech** [comment] 2021-12-28 01:05
Same issue here, [removing sentry-expo plugin](https://github.com/expo/sentry-expo#add-the-config-plugin) working for me

**Comment by giautm** [comment] 2021-12-28 10:22
@jereztech, please provide more information: sdk version, sentry-expo version. I have been build success with SDKv43 and v44

**Comment by jereztech** [comment] 2021-12-28 13:19
hi @giautm I'm using sentry-expo@4.0.0 with SDKv43, in my case the error has been different `sentry failed: resource not found (400)` without further information. In my project the postPublish.project != expo.name, will it be something related to the name?

**Comment by giautm** [comment] 2021-12-28 14:34
> hi @giautm I'm using sentry-expo@4.0.0 with SDKv43, in my case the error has been different `sentry failed: resource not found (400)` without further information. In my project the postPublish.project != expo.name, will it be something related to the name?

I think it related to Sentry config, please double-check your API keys, project name, org on Sentry. It's not related to expo.name.

**Comment by jereztech** [comment] 2021-12-28 14:37
I have copy/paste directly from Sentry, so this config is ok
