### ISSUE TITLE
Expo-Sentry: Error uploading sourcemaps to Sentry: project not found

### ISSUE THREAD

**Issue by seyaobey-dev** [expo/sentry-expo#237] opened 2022-02-13 22:15 UTC
### Summary

When I build my managed app with `eas build`, remote build fails with error:

`Error uploading sourcemaps to Sentry: project not found`

I have carefully followed the official sentr-expo documentation [Using Sentry - Expo Documentation](https://docs.expo.dev/guides/using-sentry/).
I have created a new project on https://sentry.io/. And in my app.json, I have setup the “postPublish” hooks like so:

```
"hooks": {
  "postPublish": [
    {
      "file": "sentry-expo/upload-sourcemaps",
      "config": {
        "organization": "__org_name__",
        "project": "__project_name__",
        "authToken": "__authtoken__",
        "setCommits": true
      }
    }
  ]
},
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

```
  Expo CLI 5.1.2 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.3.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2/13C5081f - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.1.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. create a new expo application
2. create a new project on `sentrio.io`
3. setup `sentry-expo` in your application as per the documentation https://docs.expo.dev/guides/using-sentry/
4. make first build with `eas build`
5. observe the error `Error uploading sourcemaps to Sentry: project not found` printed in console

**Comment by mattwigham** [comment] 2022-02-18 20:18
Having the same issue with the following in my `app.config.js`:

```
  hooks: {
    postPublish: [
      {
        file: "sentry-expo/upload-sourcemaps",
        config: {
          organization: process.env.SENTRY_ORG,
          project: process.env.SENTRY_PROJECT,
          authToken: process.env.SENTRY_AUTH_TOKEN,
        },
      },
    ],
  },
```

Presents a similar error: 

```
Error uploading sourcemaps to Sentry: An organization slug is required (provide with --org)
```

Commenting out the `hooks` config makes everything work fine, just without sourcemaps.

**Comment by stuckj** [comment] 2022-03-01 18:02
I'm hitting this same issues using SDK 43. Same setup. Expo managed workflow using EAS builds.

**Comment by stuckj** [comment] 2022-03-01 18:48
> I'm hitting this same issue using SDK 43. Same setup. Expo managed workflow using EAS builds.

Oh man. It turned out for us the problem was very simple. Someone had renamed the project name in sentry's UI so it no longer matched the project name in the `postPublish` configuration. Be sure to check that your project name matches if you're hitting this. :-P

**Comment by seyaobey-dev** [comment] 2022-03-11 15:20
I'm still getting the same error, I have verified and double-verified that my organisation name, project name and authToken (defined in postPublish key of app.json) are correct. But no luck

**Comment by devmasterji** [comment] 2022-05-12 07:53
> I'm still getting the same error, I have verified and double-verified that my organisation name, project name and authToken (defined in postPublish key of app.json) are correct. But no luck

Hi @seyaobey-dev, Even I am facing the same issue. I have verified all my configuration but still hitting the same issue. Did your issue got resolved? If yes, can you update it here.

**Comment by leszekkazmierczak** [comment] 2022-05-30 07:32
Same problem. SDK 45.0. I've set up a new Sentry project with different name, and provided details in app.json but still getting the same error. Please, anyone can help?

**Comment by Ryanjso** [comment] 2022-07-01 17:48
> Same problem. SDK 45.0. I've set up a new Sentry project with different name, and provided details in app.json but still getting the same error. Please, anyone can help?

Same

**Comment by kbrandwijk** [comment] 2022-07-17 05:11
Make sure your authToken have the correct permissions (`org:read`, `project:releases`, and `project:write`), and that the spelling and casing of your project is exactly as show in Sentry.

I'm going to close this assuming user error as I am unable to reproduce this on a clean SDK 45 project, with a clean Sentry project.

**Closed by kbrandwijk** 2022-07-17 05:11 UTC

**Comment by PeteMosafe** [comment] 2022-07-18 01:58
For anyone still struggling - i tried all the above and no joy but then I managed to solve it by fixing the organisation name in my config. 

My organization value in config had an uppercase first-letter but turns out it needs to be all lowercase. I noticed that it's all lowercase in the sentry web url `https://sentry.io/organizations/orgname/ ` so i tried and it worked

Looks like the api makes an http call to `POST https://sentry.io/api/0/projects/orgname/my-project-path/releases/` and this path is case sensitive

```
hooks: {
        postPublish: [
            {
                "file": "sentry-expo/upload-sourcemaps",
                "config": {
                    "organization": "Orgname", <-- should be "orgname"
                    "project": "my-project-path",
                    "authToken": "my-auth-token"
                }
            }
        ]
    }
```

**Comment by pwellner** [comment] 2022-07-24 20:05
@PeteMosafe Thank you!  That fixed my issue as well.
This is a bug in the `postPublish` hook.  It should downcase the `organization` before using it in the sentry URL. https://github.com/expo/sentry-expo/issues/273
